"""Briefing assembly - orchestrates all modules into a daily briefing."""

from datetime import date
from pathlib import Path

from . import tasks, habits, metrics, papers, news, substack, focus


def generate_briefing(config: dict, interests: dict, project_root: str) -> dict:
    """Generate the complete daily briefing.

    Args:
        config: Parsed settings.yaml
        interests: Parsed interests.yaml
        project_root: Absolute path to project root

    Returns:
        Dict with 'markdown' (full briefing text) and 'sections' (individual parts)
    """
    root = Path(project_root)
    paths = config.get("paths", {})
    today = date.today()
    date_str = today.isoformat()

    # 1. Personal metrics (needed first for energy-aware task prioritization)
    metrics_path = str(root / paths.get("metrics", "data/metrics.json"))
    metrics_data = metrics.analyze_metrics(metrics_path)

    # 2. Task prioritization (uses metrics for energy-aware ordering)
    tasks_path = str(root / paths.get("tasks", "data/tasks.json"))
    task_data = tasks.prioritize_tasks(tasks_path, metrics_data)

    # 3. Habit analysis (with metrics for correlations)
    habits_path = str(root / paths.get("habits", "data/habits.json"))
    metrics_raw = metrics.load_metrics(metrics_path)
    habit_data = habits.analyze_habits(habits_path, metrics_raw.get("entries", []))

    # 4. Paper recommendations
    paper_history_path = str(root / paths.get("paper_history", "data/paper_history.json"))
    paper_config = config.get("papers", {})
    paper_data = papers.get_paper_recommendations(
        paper_history_path,
        paper_config.get("search_queries", ["LLM routing"]),
        paper_config.get("categories", ["cs.CL", "cs.AI"]),
    )

    # 5. News
    news_config = config.get("news", {})
    news_data = news.fetch_all_news(news_config)

    # 6. Substack recommendation
    substack_feeds = interests.get("substack", {}).get("feeds", [])
    substack_topics = interests.get("substack", {}).get("topics", [])
    substack_post = substack.recommend_post(substack_feeds, substack_topics)

    # 7. Focus plan (combines everything)
    focus_data = focus.generate_focus_plan(task_data, habit_data, metrics_data)

    # Assemble markdown
    sections = {
        "header": _format_header(date_str),
        "focus": focus.format_focus_section(focus_data),
        "tasks": tasks.format_tasks_section(task_data),
        "habits": habits.format_habits_section(habit_data),
        "metrics": metrics.format_metrics_section(metrics_data),
        "papers": papers.format_papers_section(paper_data),
        "substack": substack.format_substack_section(substack_post),
        "news": news.format_news_section(news_data),
    }

    # Combine all sections
    markdown = "\n".join([
        sections["header"],
        sections["focus"],
        sections["tasks"],
        sections["habits"],
        sections["metrics"],
        sections["papers"],
        sections["substack"],
        sections["news"],
        _format_footer(),
    ])

    return {
        "markdown": markdown,
        "date": date_str,
        "sections": sections,
    }


def save_briefing(briefing: dict, briefings_dir: str):
    """Save briefing as a dated markdown file."""
    dir_path = Path(briefings_dir)
    dir_path.mkdir(parents=True, exist_ok=True)

    filepath = dir_path / f"{briefing['date']}.md"
    with open(filepath, "w") as f:
        f.write(briefing["markdown"])

    print(f"[Briefing] Saved to {filepath}")
    return str(filepath)


def _format_header(date_str: str) -> str:
    from datetime import datetime
    d = datetime.fromisoformat(date_str)
    day_name = d.strftime("%A")
    formatted = d.strftime("%B %d, %Y")
    return (
        f"# Mochi's Daily Briefing\n"
        f"**{day_name}, {formatted}**\n"
        f"---\n"
    )


def _format_footer() -> str:
    return (
        "---\n"
        "*Generated by Mochi's Assistant*\n"
        "*Update your data in the `data/` folder. "
        "Run `python src/main.py` anytime for an on-demand briefing.*\n"
    )
